AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
